# Generated by Django 5.1.1 on 2024-10-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'verbose_name': 'Employment History', 'verbose_name_plural': 'Employment Histories'},
        ),
    ]
